global:
  resolve_timeout: 5m

route:
  receiver: "default"
  group_by: ["alertname", "component"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  routes:
    - receiver: "critical-pagerduty"
      matchers:
        - severity="critical"
        - paging_provider="pagerduty"
      continue: true
    - receiver: "critical-opsgenie"
      matchers:
        - severity="critical"
        - paging_provider="opsgenie"
      continue: true
    - receiver: "critical-paging-webhook"
      matchers:
        - severity="critical"
      continue: true
    - receiver: "critical-telegram"
      matchers:
        - severity="critical"
      continue: true
    - receiver: "high-telegram"
      matchers:
        - severity="high"
      continue: true
    - receiver: "warning-email"
      matchers:
        - severity=~"warning|high|critical"

receivers:
  - name: "default"
  - name: "critical-pagerduty"
  - name: "critical-opsgenie"
  - name: "critical-paging-webhook"
  - name: "critical-telegram"
  - name: "high-telegram"
  - name: "warning-email"
